//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Resources.ProgramMessages", typeof(ProgramMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الاتصال بمزود قاعدة البيانات نتيجة خطأ في ضبط المزود أو الشبكة,اتصل بمدير الشبكة لإصلاح هذا العطل..
        /// </summary>
        internal static string ErrMesConnFailed {
            get {
                return ResourceManager.GetString("ErrMesConnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك قم بتنصيب برنامج التقارير.
        /// </summary>
        internal static string ErrMesCrystalRepInstallation {
            get {
                return ResourceManager.GetString("ErrMesCrystalRepInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قاعدة البيانات غير موجودة على المزود المحدد..
        /// </summary>
        internal static string ErrMesDBDoseNotExist {
            get {
                return ResourceManager.GetString("ErrMesDBDoseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد قاعدة بيانات بنفس الاسم على الخادم من فضلك ، اختر اسم آخر لقاعدة البيانات..
        /// </summary>
        internal static string ErrMesDBExist {
            get {
                return ResourceManager.GetString("ErrMesDBExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجلد المختار لاسترجاع البيانات به ملفات قاعدة البيانات. من فضلك اختر مجلد آخر ..
        /// </summary>
        internal static string ErrMesDBFIlesExist {
            get {
                return ResourceManager.GetString("ErrMesDBFIlesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجلد المختار لإنشاء ملفات قواعد البيانات فيه غير موجود من فضلك أنشئه اولاً..
        /// </summary>
        internal static string ErrMesDBFolderDoseNotExist {
            get {
                return ResourceManager.GetString("ErrMesDBFolderDoseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم ظهور هذا الخطأ :.
        /// </summary>
        internal static string ErrMesErrorOccured {
            get {
                return ResourceManager.GetString("ErrMesErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك قم بتنصيب أول نسخة من البرنامج على الجهاز الخاص بخادم قاعدة البيانات مباشرة. ثم اتصل به من جهاز الموظف..
        /// </summary>
        internal static string ErrMesInstallDBOnServer {
            get {
                return ResourceManager.GetString("ErrMesInstallDBOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور خطأ..
        /// </summary>
        internal static string ErrMesInvalidSQLUsr {
            get {
                return ResourceManager.GetString("ErrMesInvalidSQLUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف استرجاع خاطئ..
        /// </summary>
        internal static string ErrMesInvBckpFile {
            get {
                return ResourceManager.GetString("ErrMesInvBckpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لملف الأرشيف غير صحيحة..
        /// </summary>
        internal static string ErrMesInvBckpFilePass {
            get {
                return ResourceManager.GetString("ErrMesInvBckpFilePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الذاكرة ممتلئة سيتم إغلاق البرنامج..
        /// </summary>
        internal static string ErrMesMemoryFull {
            get {
                return ResourceManager.GetString("ErrMesMemoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد سجلات مرتبطة بهذا السجل من فضلك احذفها أولاً..
        /// </summary>
        internal static string ErrMesRelRec {
            get {
                return ResourceManager.GetString("ErrMesRelRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خادم البيانات غير متاح أو لا يسمح بالاتصال عن بعد..
        /// </summary>
        internal static string ErrMesServerExist {
            get {
                return ResourceManager.GetString("ErrMesServerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخادم الذي تتصل به لا يستجيب أو نفذ الوقت المسموح به للاتصال بالخادم.  من فضل أصلح هذه المشكلة ثم حاول مرة أخرى..
        /// </summary>
        internal static string ErrMesServerNotResponding {
            get {
                return ResourceManager.GetString("ErrMesServerNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقول المزودة لا توجد في الجدول المزود.
        /// </summary>
        internal static string ErrMesTblClms {
            get {
                return ResourceManager.GetString("ErrMesTblClms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم عمل نسخة احتياطية بنجاح. مسار ملف النسخة الاحتياطية :.
        /// </summary>
        internal static string MesBackupSuccessfull {
            get {
                return ResourceManager.GetString("MesBackupSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لن يمكنك الكتابة في هذا الحقل لعدم توفر لغة مناسبة له..
        /// </summary>
        internal static string MesCantWriteInField {
            get {
                return ResourceManager.GetString("MesCantWriteInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاتصال بقاعدة البيانات بنجاح..
        /// </summary>
        internal static string MesConnectSuccessfull {
            get {
                return ResourceManager.GetString("MesConnectSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف السجل الحالي؟.
        /// </summary>
        internal static string MesDeleteConfirm {
            get {
                return ResourceManager.GetString("MesDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موجود..
        /// </summary>
        internal static string MesDosntExist {
            get {
                return ResourceManager.GetString("MesDosntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا لم تختار كلمة مرور فبإمكان أي أحد استرجاع البيانات. هل أنت متأكد؟.
        /// </summary>
        internal static string MesEmptyBackupPwd {
            get {
                return ResourceManager.GetString("MesEmptyBackupPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج مدير الأصناف.
        /// </summary>
        internal static string MesHeader {
            get {
                return ResourceManager.GetString("MesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول خاطئ..
        /// </summary>
        internal static string MesInvalidLogin {
            get {
                return ResourceManager.GetString("MesInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم خاطئ..
        /// </summary>
        internal static string MesInvalidUser {
            get {
                return ResourceManager.GetString("MesInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameAr.
        /// </summary>
        internal static string MesNameField {
            get {
                return ResourceManager.GetString("MesNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد أي لغة من لغات الإدخال للغة العربية. من فضلك قم بتنصيب لغة عربية للإدخال ثم أعد المحاولة..
        /// </summary>
        internal static string MesNoArabicInput {
            get {
                return ResourceManager.GetString("MesNoArabicInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد أي لغة من لغات الإدخال للغة الإنجليزية. من فضلك قم بتنصيب لغة إنجليزية للإدخال ثم أعد المحاولة..
        /// </summary>
        internal static string MesNoEnglishInput {
            get {
                return ResourceManager.GetString("MesNoEnglishInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار :  .
        /// </summary>
        internal static string MesPath {
            get {
                return ResourceManager.GetString("MesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استرجاع البيانات بنجاح..
        /// </summary>
        internal static string MesRestoreSuccessfull {
            get {
                return ResourceManager.GetString("MesRestoreSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إيقاف خادم البيانات أو خاجم البيانات غير متصل..
        /// </summary>
        internal static string MesSqlServerStopped {
            get {
                return ResourceManager.GetString("MesSqlServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل الأول.
        /// </summary>
        internal static string MsgFirtsRecord {
            get {
                return ResourceManager.GetString("MsgFirtsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل الأخير.
        /// </summary>
        internal static string MsgLastRecord {
            get {
                return ResourceManager.GetString("MsgLastRecord", resourceCulture);
            }
        }
    }
}
