//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemsManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItemsManager.Resources.ProgramMessages", typeof(ProgramMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الملف الأرشيفي لقاعدة البيانات..
        /// </summary>
        internal static string ErrMesChooseBackupFile {
            get {
                return ResourceManager.GetString("ErrMesChooseBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر بيان صحيح..
        /// </summary>
        internal static string ErrMesChooseValidData {
            get {
                return ResourceManager.GetString("ErrMesChooseValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عملية صحيحة..
        /// </summary>
        internal static string ErrMesChooseValidOperation {
            get {
                return ResourceManager.GetString("ErrMesChooseValidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال تحويل هذه الوحدة لهذا الصنف من قبل..
        /// </summary>
        internal static string ErrMesConversionEnteredForItem {
            get {
                return ResourceManager.GetString("ErrMesConversionEnteredForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجلد المختار لاسترجاع البيانات به ملفات قاعدة البيانات. من فضلك اختر مجلد آخر ..
        /// </summary>
        internal static string ErrMesDBFilesExit {
            get {
                return ResourceManager.GetString("ErrMesDBFilesExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كلمة المرور لملف أرشيف قاعدة البيانات..
        /// </summary>
        internal static string ErrMesEnterBackupFilePassword {
            get {
                return ResourceManager.GetString("ErrMesEnterBackupFilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المسار الذي سيتم إنشاء قاعدة البيانات فيه..
        /// </summary>
        internal static string ErrMesEnterBackupPath {
            get {
                return ResourceManager.GetString("ErrMesEnterBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل تصنيفات الأصناف أولاً.
        /// </summary>
        internal static string ErrMesEnterCategoriesFirst {
            get {
                return ResourceManager.GetString("ErrMesEnterCategoriesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم قاعدة البيانات..
        /// </summary>
        internal static string ErrMesEnterDBName {
            get {
                return ResourceManager.GetString("ErrMesEnterDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل أصناف أولاً..
        /// </summary>
        internal static string ErrMesEnterItmes {
            get {
                return ResourceManager.GetString("ErrMesEnterItmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم مزود قاعدة البيانات..
        /// </summary>
        internal static string ErrMesEnterServerName {
            get {
                return ResourceManager.GetString("ErrMesEnterServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل وحدات أولاً.
        /// </summary>
        internal static string ErrMesEnterUnitsFirst {
            get {
                return ResourceManager.GetString("ErrMesEnterUnitsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل أنواع الوحدات أولاً.
        /// </summary>
        internal static string ErrMesEnterUnitsTypesFirst {
            get {
                return ResourceManager.GetString("ErrMesEnterUnitsTypesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم المستخدم لمزود قاعدة البيانات..
        /// </summary>
        internal static string ErrMesEnterUserName {
            get {
                return ResourceManager.GetString("ErrMesEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل سعر صحيح..
        /// </summary>
        internal static string ErrMesEnterValidPrice {
            get {
                return ResourceManager.GetString("ErrMesEnterValidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كمية صحيحة..
        /// </summary>
        internal static string ErrMesEnterValidQuantity {
            get {
                return ResourceManager.GetString("ErrMesEnterValidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تسجيل أكثر من عملة إفتراضية.
        /// </summary>
        internal static string ErrMesExistDefaultCurrency {
            get {
                return ResourceManager.GetString("ErrMesExistDefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية الموجودة أكبر من الكمية المحسوبة..
        /// </summary>
        internal static string ErrMesExistingQuantityBiggerThanCalculated {
            get {
                return ResourceManager.GetString("ErrMesExistingQuantityBiggerThanCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية أكبر من تاريخ النهاية..
        /// </summary>
        internal static string ErrMesFromDateBiggerThanToDate {
            get {
                return ResourceManager.GetString("ErrMesFromDateBiggerThanToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قاعدة البيانات غير صحيحة..
        /// </summary>
        internal static string ErrMesInvalidDatabase {
            get {
                return ResourceManager.GetString("ErrMesInvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم صحيح.
        /// </summary>
        internal static string ErrMesInvalidNumber {
            get {
                return ResourceManager.GetString("ErrMesInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجدول غير صحيح..
        /// </summary>
        internal static string ErrMesInvldTblName {
            get {
                return ResourceManager.GetString("ErrMesInvldTblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الصنف تم إضافته من قبل لهذا الجزء من المشروع..
        /// </summary>
        internal static string ErrMesItemAlreadyExists {
            get {
                return ResourceManager.GetString("ErrMesItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الصنف لديه وحدة رئيسية أخرى..
        /// </summary>
        internal static string ErrMesItemAlreadyHaveDefaultUnit {
            get {
                return ResourceManager.GetString("ErrMesItemAlreadyHaveDefaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إدخال هذا الصنف من قبل..
        /// </summary>
        internal static string ErrMesItemEntered {
            get {
                return ResourceManager.GetString("ErrMesItemEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد أصناف في المتجر..
        /// </summary>
        internal static string ErrMesNoItemsExist {
            get {
                return ResourceManager.GetString("ErrMesNoItemsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك إختر عملة للتحويل إليها مختلفة عن العملة المحول منها .
        /// </summary>
        internal static string ErrMesSameCurryeny {
            get {
                return ResourceManager.GetString("ErrMesSameCurryeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن عمل السجل بنفس الأب..
        /// </summary>
        internal static string ErrMesSameParent {
            get {
                return ResourceManager.GetString("ErrMesSameParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود مسجل من قبل..
        /// </summary>
        internal static string ErrMessExistBankCode {
            get {
                return ResourceManager.GetString("ErrMessExistBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم العربى مسجل من قبل..
        /// </summary>
        internal static string ErrMessExistBankNameAr {
            get {
                return ResourceManager.GetString("ErrMessExistBankNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم الانجليزى مسجل من قبل.
        /// </summary>
        internal static string ErrMessExistBankNameEn {
            get {
                return ResourceManager.GetString("ErrMessExistBankNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود مسجل من قبل..
        /// </summary>
        internal static string ErrMessExistCode {
            get {
                return ResourceManager.GetString("ErrMessExistCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم مسجل من قبل..
        /// </summary>
        internal static string ErrMessExistNameAr {
            get {
                return ResourceManager.GetString("ErrMessExistNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم الاجنبي مسجل من قبل.
        /// </summary>
        internal static string ErrMessExistNameEn {
            get {
                return ResourceManager.GetString("ErrMessExistNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إغلاق الوردية بنجاح..
        /// </summary>
        internal static string ErrMesShiftClosed {
            get {
                return ResourceManager.GetString("ErrMesShiftClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن التحويل إلى نفس الوحدة..
        /// </summary>
        internal static string ErrMesToAndFromUnitsEqual {
            get {
                return ResourceManager.GetString("ErrMesToAndFromUnitsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إدخال هذه التحويلة من قبل..
        /// </summary>
        internal static string ErrMesUnitConversionEntered {
            get {
                return ResourceManager.GetString("ErrMesUnitConversionEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إدخال هذه الوحدة لهذا الصنف من قبل..
        /// </summary>
        internal static string ErrMesUnitIsEnteredForItem {
            get {
                return ResourceManager.GetString("ErrMesUnitIsEnteredForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود من قبل..
        /// </summary>
        internal static string ErrMesUserNameExist {
            get {
                return ResourceManager.GetString("ErrMesUserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم عمل نسخة احتياطية بنجاح مسار ملف الأرشيف :.
        /// </summary>
        internal static string MesBackupSuccessfull {
            get {
                return ResourceManager.GetString("MesBackupSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الملف لا يمكن أن يتعدى 2 جيجا بايت !!!.
        /// </summary>
        internal static string MesBigFileSize {
            get {
                return ResourceManager.GetString("MesBigFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف أو تعديل فاتورة تم الجرد بعدها..
        /// </summary>
        internal static string MesCantDeleteInvoiceAfterStocktaking {
            get {
                return ResourceManager.GetString("MesCantDeleteInvoiceAfterStocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف أو تعديل إدخال الأصناف تم الجرد بعده..
        /// </summary>
        internal static string MesCantDeleteItemsInAfterStocktaking {
            get {
                return ResourceManager.GetString("MesCantDeleteItemsInAfterStocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في هذا النموذج لا بد من اختيار سجل للاستمرار..
        /// </summary>
        internal static string MesChooseInsertRecord {
            get {
                return ResourceManager.GetString("MesChooseInsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عنصر أولاً..
        /// </summary>
        internal static string MesChooseItem {
            get {
                return ResourceManager.GetString("MesChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر سجل لحذفه.
        /// </summary>
        internal static string MesChooseRecordToDelete {
            get {
                return ResourceManager.GetString("MesChooseRecordToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر صف لعرضه..
        /// </summary>
        internal static string MesChooseShowRecord {
            get {
                return ResourceManager.GetString("MesChooseShowRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر صف لتعديله..
        /// </summary>
        internal static string MesChooseUpdateRecord {
            get {
                return ResourceManager.GetString("MesChooseUpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string MesClients {
            get {
                return ResourceManager.GetString("MesClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متاكد من حذف البيانات.
        /// </summary>
        internal static string MesConfirmDeleteAllData {
            get {
                return ResourceManager.GetString("MesConfirmDeleteAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاتصال بقاعدة البيانات بنجاح..
        /// </summary>
        internal static string MesConnectSuccessfull {
            get {
                return ResourceManager.GetString("MesConnectSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        internal static string MesDataNotSaved {
            get {
                return ResourceManager.GetString("MesDataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف السجل الحالي؟.
        /// </summary>
        internal static string MesDeleteConfirm {
            get {
                return ResourceManager.GetString("MesDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف السجل بنجاح..
        /// </summary>
        internal static string MesDeleteSuccessfull {
            get {
                return ResourceManager.GetString("MesDeleteSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  غير موجود..
        /// </summary>
        internal static string MesDosntExist {
            get {
                return ResourceManager.GetString("MesDosntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد استبدال الكمية؟.
        /// </summary>
        internal static string MesDoYouWantToExchangeQuantities {
            get {
                return ResourceManager.GetString("MesDoYouWantToExchangeQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند عدم اختيار كلمة مرور يمكن لأي شخص استرجاع البيانات. هل أنت متأكد؟.
        /// </summary>
        internal static string MesEmptyBackupPwd {
            get {
                return ResourceManager.GetString("MesEmptyBackupPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المختار إما تالف أو فارغ..
        /// </summary>
        internal static string MesEmptyOrBadFile {
            get {
                return ResourceManager.GetString("MesEmptyOrBadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البيان مطلوب.
        /// </summary>
        internal static string MesEnterField {
            get {
                return ResourceManager.GetString("MesEnterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الصنف غير مسجل..
        /// </summary>
        internal static string MesEnterNewItem {
            get {
                return ResourceManager.GetString("MesEnterNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ. هل تريد الحفظ الآن؟.
        /// </summary>
        internal static string MesExitFormConfirm {
            get {
                return ResourceManager.GetString("MesExitFormConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المختار تم حذفه أو غير موجود.
        /// </summary>
        internal static string MesFileDosntExist {
            get {
                return ResourceManager.GetString("MesFileDosntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أول سجل..
        /// </summary>
        internal static string MesFirstRecord {
            get {
                return ResourceManager.GetString("MesFirstRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل أنواع المصاريف أولاً..
        /// </summary>
        internal static string MesInsertExpencesTypes {
            get {
                return ResourceManager.GetString("MesInsertExpencesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول خاطئ..
        /// </summary>
        internal static string MesInvalidLogin {
            get {
                return ResourceManager.GetString("MesInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور خاطئ..
        /// </summary>
        internal static string MesInvalidPassConf {
            get {
                return ResourceManager.GetString("MesInvalidPassConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم خاطئ..
        /// </summary>
        internal static string MesInvalidUser {
            get {
                return ResourceManager.GetString("MesInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر سجل..
        /// </summary>
        internal static string MesLastRecord {
            get {
                return ResourceManager.GetString("MesLastRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameAr.
        /// </summary>
        internal static string MesNameField {
            get {
                return ResourceManager.GetString("MesNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يحدث أي تغيير في البيانات.
        /// </summary>
        internal static string MesNoChangeDone {
            get {
                return ResourceManager.GetString("MesNoChangeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات لعرضها..
        /// </summary>
        internal static string MesNoDataToDisplay {
            get {
                return ResourceManager.GetString("MesNoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد أي كمية من هذا الصنف..
        /// </summary>
        internal static string MesNoExistingItemQuantity {
            get {
                return ResourceManager.GetString("MesNoExistingItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجدت وحدات تم تعريفها على هذا الصنف..
        /// </summary>
        internal static string MesNoExistingItemUnit {
            get {
                return ResourceManager.GetString("MesNoExistingItemUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملف لعرضه..
        /// </summary>
        internal static string MesNoFileToDisplay {
            get {
                return ResourceManager.GetString("MesNoFileToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد نتائج.
        /// </summary>
        internal static string MesNoResultsFound {
            get {
                return ResourceManager.GetString("MesNoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا تقل عن أربعة حروف..
        /// </summary>
        internal static string MesPassrdNotLess4Char {
            get {
                return ResourceManager.GetString("MesPassrdNotLess4Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار : .
        /// </summary>
        internal static string MesPath {
            get {
                return ResourceManager.GetString("MesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البيان مطلوب.
        /// </summary>
        internal static string MesRequiredField {
            get {
                return ResourceManager.GetString("MesRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت عدد محاولات إسترجاع كلمة المرور وسوف يتم إغلاق البرنامج..
        /// </summary>
        internal static string MesRestoreLimitReached {
            get {
                return ResourceManager.GetString("MesRestoreLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في البيانات . من فضلك تأكد من البيانات المدخلة.
        /// </summary>
        internal static string MesRestorePasswordErr {
            get {
                return ResourceManager.GetString("MesRestorePasswordErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استرجاع البيانات بنجاح..
        /// </summary>
        internal static string MesRestoreSuccessfull {
            get {
                return ResourceManager.GetString("MesRestoreSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الحفظ؟.
        /// </summary>
        internal static string MesSaveConfirm {
            get {
                return ResourceManager.GetString("MesSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        internal static string MesSaveSuccessfull {
            get {
                return ResourceManager.GetString("MesSaveSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصروفات الوردية رقم.
        /// </summary>
        internal static string MesShifNo {
            get {
                return ResourceManager.GetString("MesShifNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سارية.
        /// </summary>
        internal static string MesShiftContinous {
            get {
                return ResourceManager.GetString("MesShiftContinous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتهية.
        /// </summary>
        internal static string MesShiftEnded {
            get {
                return ResourceManager.GetString("MesShiftEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد الأخطاء التالية :.
        /// </summary>
        internal static string MesThereIsTheFollowingErrors {
            get {
                return ResourceManager.GetString("MesThereIsTheFollowingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد التعديل؟.
        /// </summary>
        internal static string MesUpdateConfirm {
            get {
                return ResourceManager.GetString("MesUpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم تم استخدامه من قبل في البرنامج..
        /// </summary>
        internal static string MesUserNameUsed {
            get {
                return ResourceManager.GetString("MesUserNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمون.
        /// </summary>
        internal static string MesUsers {
            get {
                return ResourceManager.GetString("MesUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك، استخدم لغة مناسبة لهذا الحقل..
        /// </summary>
        internal static string MesUseSuitableLanguage {
            get {
                return ResourceManager.GetString("MesUseSuitableLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا يقل عن أربعة حروف..
        /// </summary>
        internal static string MesUsrNameNotLess4Char {
            get {
                return ResourceManager.GetString("MesUsrNameNotLess4Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد هذه الكمية من هذا الصنف الكمية الموجودة = .
        /// </summary>
        internal static string MesVeryBigItemQuantity {
            get {
                return ResourceManager.GetString("MesVeryBigItemQuantity", resourceCulture);
            }
        }
    }
}
